spring:
  application:
    name: WeatherApiAssessment
  datasource:
    url: jdbc:mysql://localhost:3306/delhi_weather
    username: root
    password: "1234567890#"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
batch:
  file:
    path: src/main/resources/